let curr_vid_id = 0;
let vid_focussed = true;
let vid_loop = false;
let new_vid_data_arr;
let curr_duration;
let vid_vol = getCookie("vid_vol") || 0.2;
let play_history= new Array();
let prev_id=0;
let prev_id_count=0;
let first_src;
let justHidden = false;
let oppositeday = false;
let customcode = true;
let last_vid_id = 0;
let total_vids = 0;
let new_playlist_all_array; 
let client_url;
let is_mousedownvid = false;
let earlymouseX, earlymouseY;
let mouseX, mouseY;
let longmousedown = false;
let longmousedowntimout;
let first_subs;
const {ipcRenderer} = require("electron");
//const electron = require("electron");
